; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                      = 10191107-x86_64 Linux                   
[ DataSettings ]
datatype                                 = snNucleotide                            
containsCodingNuc                        = True                                    
MissingBaseSymbol                        = ?                                       
IdenticalBaseSymbol                      = .                                       
GapSymbol                                = -                                       
Labelled Sites                           = All Sites                               
Labels to Include                        =                                         
[ ProcessTypes ]
ppInfer                                  = true                                    
ppNJ                                     = true                                    
[ AnalysisSettings ]
Analysis                                 = Phylogeny Reconstruction                
Scope                                    = All Selected Taxa                       
Statistical Method                       = Neighbor-joining                        
Phylogeny Test                           = ====================                    
Test of Phylogeny                        = Bootstrap method                        
No. of Bootstrap Replications            = 1000                                    
Substitution Model                       = ====================                    
Substitutions Type                       = Nucleotide                              
Model/Method                             = Jukes-Cantor model                      
Fixed Transition/Transversion Ratio      = Not Applicable                          
Substitutions to Include                 = All                                     
Rates and Patterns                       = ====================                    
Rates among Sites                        = Gamma Distributed (G)                   
Gamma Parameter                          = 1.00                                    
Pattern among Lineages                   = Same (Homogeneous)                      
Data Subset to Use                       = ====================                    
Gaps/Missing Data Treatment              = Pairwise deletion                       
Site Coverage Cutoff (%)                 = Not Applicable                          
Select Codon Positions                   = 1st, 2nd, 3rd, Non-Coding               
System Resource Usage                    = ====================                    
Number of Threads                        = 16                                      
Genetic Code Table                       = Not Applicable                          
Genetic Code                             = Not Applicable                          
Has Time Limit                           = False                                   
Maximum Execution Time                   = -1                                      
